version: "3"
services:
  serve:
    container_name: dlbad-nodejs-api
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - ${PORT}
    restart: always
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
