name: deploy to prod
on:
  release:
    types: [published]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/ayberkcakar/dlbad-service:${{ env.RELEASE_VERSION }}, ghcr.io/ayberkcakar/dlbad-service:latest
          platforms: linux/amd64,linux/arm64